In [34]:
import numpy as np

In [35]:
#1D array
arr=np.array(([11,22,3]))
print(arr)

[11 22  3]


In [36]:
type(arr), arr.shape

(numpy.ndarray, (3,))

In [37]:
#2D array
arr2=np.array(([1,22,3],[4,5,6],[7,8,9]))
print(arr2)
arr.shape

[[ 1 22  3]
 [ 4  5  6]
 [ 7  8  9]]


(3,)

In [38]:
# Creating an ndarray
arrN=np.array(([[1,2,3],[3,4,5]],[[37,43,52],[6,7,8]]))
print(arrN)

# Properties of ndarray
print(arrN.ndim)
print(arrN.shape)
print(arrN.dtype)

[[[ 1  2  3]
  [ 3  4  5]]

 [[37 43 52]
  [ 6  7  8]]]
3
(2, 2, 3)
int64


In [39]:
arr4=np.array([1,2,3,4,4], dtype="float64")
print(arr4, arr4.dtype)

[1. 2. 3. 4. 4.] float64


In [40]:
# Complex dtype
arr_c=np.array([1+2j, 3+4j])
print(arr_c, arr_c.dtype)

[1.+2.j 3.+4.j] complex128


In [41]:
arr=np.array([1,2,3,4,5])

In [42]:

print(arr+10)
print(arr*2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [43]:
arr

array([1, 2, 3, 4, 5])

In [44]:
print(arr.sum())
print(arr.mean())
print(arr.max())

15
3.0
5


In [45]:
arr=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [46]:
print(arr+arr2)
print(arr*arr2)

[ 6  8 10 12]
[ 5 12 21 32]


ARRAY slicing

In [47]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [48]:
print(arr[0])
print(arr[-2])

10
40


In [49]:
#slice
print(arr[1:3])
print(arr[-4:-2])

[20 30]
[20 30]


In [50]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

Advanced Indexing

In [51]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr.ndim)
print(arr.shape)
print(arr[-1])

2
(3, 3)
[3 4 5]


In [52]:
arr*=11

In [53]:
print(arr)

[[11 22 33]
 [22 33 44]
 [33 44 55]]


In [54]:
print(arr>35)

[[False False False]
 [False False  True]
 [False  True  True]]


In [55]:
print(arr[True].shape)

(1, 3, 3)


In [56]:
for row in arr:
    for element in row:
        print(element, end="R ")
    print()    

11R 22R 33R 
22R 33R 44R 
33R 44R 55R 


In [57]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [58]:
print(arr*3)

[ 3  6  9 12 15 18 21 24 27 30]


In [59]:
print(arr.max())
print(arr.mean())

10
5.5


In [60]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [61]:
b=np.ones((5,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [63]:
c=np.full((5,7),8)
print(c)

[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [67]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
e=np.random.random((2,2))
print(e)

[[0.89756223 0.67482392]
 [0.38175299 0.80069133]]
