In [85]:
import numpy as np

In [86]:
#1D array
arr=np.array(([11,22,3]))
print(arr)

[11 22  3]


In [87]:
type(arr), arr.shape

(numpy.ndarray, (3,))

In [88]:
#2D array
arr2=np.array(([1,22,3],[4,5,6],[7,8,9]))
print(arr2)
arr.shape

[[ 1 22  3]
 [ 4  5  6]
 [ 7  8  9]]


(3,)

In [89]:
# Creating an ndarray
arrN=np.array(([[1,2,3],[3,4,5]],[[37,43,52],[6,7,8]]))
print(arrN)

# Properties of ndarray
print(arrN.ndim)
print(arrN.shape)
print(arrN.dtype)

[[[ 1  2  3]
  [ 3  4  5]]

 [[37 43 52]
  [ 6  7  8]]]
3
(2, 2, 3)
int64


In [90]:
arr4=np.array([1,2,3,4,4], dtype="float64")
print(arr4, arr4.dtype)

[1. 2. 3. 4. 4.] float64


In [91]:
# Complex dtype
arr_c=np.array([1+2j, 3+4j])
print(arr_c, arr_c.dtype)

[1.+2.j 3.+4.j] complex128


In [92]:
arr=np.array([1,2,3,4,5])

In [93]:

print(arr+10)
print(arr*2)

[11 12 13 14 15]
[ 2  4  6  8 10]


In [94]:
arr

array([1, 2, 3, 4, 5])

In [95]:
print(arr.sum())
print(arr.mean())
print(arr.max())

15
3.0
5


In [96]:
arr=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [97]:
print(arr+arr2)
print(arr*arr2)

[ 6  8 10 12]
[ 5 12 21 32]


ARRAY slicing


In [98]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [99]:
print(arr[0])
print(arr[-2])

10
40


In [100]:
#slice
print(arr[1:3])
print(arr[-4:-2])

[20 30]
[20 30]


In [101]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

Advanced Indexing


In [102]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr.ndim)
print(arr.shape)
print(arr[-1])

2
(3, 3)
[3 4 5]


In [103]:
arr*=11

In [104]:
print(arr)

[[11 22 33]
 [22 33 44]
 [33 44 55]]


In [105]:
print(arr>35)

[[False False False]
 [False False  True]
 [False  True  True]]


In [106]:
print(arr[True].shape)

(1, 3, 3)


In [107]:
for row in arr:
    for element in row:
        print(element, end="R ")
    print()    

11R 22R 33R 
22R 33R 44R 
33R 44R 55R 


In [108]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [109]:
print(arr*3)

[ 3  6  9 12 15 18 21 24 27 30]


In [110]:
print(arr.max())
print(arr.mean())

10
5.5


In [111]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [112]:
b=np.ones((5,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [113]:
c=np.full((5,7),8)
print(c)

[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [114]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [115]:
e=np.random.randint(800, size=(4,8))
print(e)

[[ 72 223 459 507 543 512 434 217]
 [252 364 176 267 312 133 597 227]
 [349 748 471  90 385 485 511 506]
 [ 89 140 703 363 276 430 499 791]]


In [116]:
e[1:3]

array([[252, 364, 176, 267, 312, 133, 597, 227],
       [349, 748, 471,  90, 385, 485, 511, 506]], dtype=int32)

In [117]:
a=np.array([[1,2,3,4],[4,5,6,7],[8,9,11,12],[13,14,15,16]])

In [118]:
row_r=a[2,:]
row_r2=a[1:3,1:3]
print(row_r, row_r.shape)
print(row_r2, row_r2.shape )

[ 8  9 11 12] (4,)
[[ 5  6]
 [ 9 11]] (2, 2)


In [119]:
a[1:4, 1:3]

array([[ 5,  6],
       [ 9, 11],
       [14, 15]])

In [120]:
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 11 12]
 [13 14 15 16]]


In [121]:
col_r1=a[:,1]
col_r2=a[:, 1:3]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  5  9 14] (4,)
[[ 2  3]
 [ 5  6]
 [ 9 11]
 [14 15]] (4, 2)


In [122]:
nums=np.arange(3,17)
nums*2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [123]:
nums

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [124]:
nums*=2
nums

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [125]:
print(nums.mean())
print(nums.max())

19.0
32


In [126]:
nums=np.arange(1,13).reshape(3,4)
print(nums)
print(nums.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [127]:
np.sum(nums, axis=1)

array([10, 26, 42])

In [128]:
arr=np.array([[1,2,3],[4,5,5]])
for row in arr:
    print(row)

for element in np.nditer(arr):
    print(element)

[1 2 3]
[4 5 5]
1
2
3
4
5
5


Linear Algebra


In [129]:
arr1=np.array([[1,2,3],[5,6,7], [11,23,32]],dtype="float64")
arr2=np.array([[6,7,8],[8,9,10],[22,43,56]],dtype="float64")
print(arr1)
print(arr2)

[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [11. 23. 32.]]
[[ 6.  7.  8.]
 [ 8.  9. 10.]
 [22. 43. 56.]]


In [130]:
# Perform dot product (matrix multiplication)
print(np.dot(arr1, arr2))

[[  88.  154.  196.]
 [ 232.  390.  492.]
 [ 954. 1660. 2110.]]


In [131]:
print(arr1.T)

[[ 1.  5. 11.]
 [ 2.  6. 23.]
 [ 3.  7. 32.]]


In [132]:
# Determinant
print("Determinant",np.linalg.det(arr1))

Determinant 11.999999999999995


Sorting, Searching, and Counting

In [133]:
arr=np.array([3,45,2,4,8,2,9,12,34,3,100,5])
#sorting
print(np.sort(arr))

[  2   2   3   3   4   5   8   9  12  34  45 100]


In [134]:
# Searching
print(np.where(arr==2))

(array([2, 5]),)


In [135]:
# Counting
print(np.count_nonzero(arr==2))
print(np.sum(arr==2))
arr==3

2
2


array([ True, False, False, False, False, False, False, False, False,
        True, False, False])

Exercise

In [136]:
arr=np.random.randint(51, size=(4,5))
print(arr)

[[23  2 46 46 50]
 [44 33 25 20 50]
 [ 3 22 13  0 17]
 [45 48 15  9  2]]


In [137]:
print(arr.mean())
print(arr.T)
arr2=arr.T
print(arr2)

25.65
[[23 44  3 45]
 [ 2 33 22 48]
 [46 25 13 15]
 [46 20  0  9]
 [50 50 17  2]]
[[23 44  3 45]
 [ 2 33 22 48]
 [46 25 13 15]
 [46 20  0  9]
 [50 50 17  2]]


In [138]:
print(arr[arr>25])

[46 46 50 44 33 50 45 48]


In [139]:
# matrix multiplication between the original and transposed array
print(np.dot(arr,arr2))
print(np.linalg.det(arr1))

[[7265 5648 1561 2335]
 [5648 6550 2033 4219]
 [1561 2033  951 1420]
 [2335 4219 1420 4639]]
11.999999999999995


broadcasting

In [140]:
x=np.array([[11,22,333],[44,55,66],[77,88,99],[111,222,333],[444,555,666]])
y=np.empty_like(x)
y, y.shape

(array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408]]),
 (5, 3))

In [141]:
v=np.array([2,0,-2])
v

array([ 2,  0, -2])

In [142]:
print(x.shape[0])
print(x.shape[1])

5
3


In [143]:
for i in range(x.shape[0]): #x.shape[0] is the number of rows
    y[i,:]=x[i,:]*v
y

array([[   22,     0,  -666],
       [   88,     0,  -132],
       [  154,     0,  -198],
       [  222,     0,  -666],
       [  888,     0, -1332]])

In [144]:
v_x=np.tile(v,(5,1))
v_x

array([[ 2,  0, -2],
       [ 2,  0, -2],
       [ 2,  0, -2],
       [ 2,  0, -2],
       [ 2,  0, -2]])

In [145]:
x+v_x

array([[ 13,  22, 331],
       [ 46,  55,  64],
       [ 79,  88,  97],
       [113, 222, 331],
       [446, 555, 664]])

In [146]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
h=np.array([1,2,1,2]).reshape(4,1)
x,h

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[1],
        [2],
        [1],
        [2]]))

In [147]:
y=np.empty_like(x)
y

array([[  2,   2,   3],
       [  3,   4,   5],
       [  8,   9,  12],
       [ 34,  45, 100]])

In [148]:
for i in range(x.shape[0]):
    y[:, i:i+1]=x[:, i:i+1]+h
y

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [ 8,  9, 10],
       [12, 13, 14]])

In [149]:
h_x=np.tile(h,(1,3))
h_x

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [150]:
arr=np.random.randint(10,61, size=(4,5))
arr

array([[55, 18, 20, 40, 34],
       [13, 10, 31, 51, 31],
       [20, 51, 34, 38, 23],
       [26, 47, 39, 47, 38]], dtype=int32)

In [151]:
print(arr[0:2,:])
print(arr[:,-1])


[[55 18 20 40 34]
 [13 10 31 51 31]]
[34 31 23 38]


In [152]:
arr[arr>30]=0
arr

array([[ 0, 18, 20,  0,  0],
       [13, 10,  0,  0,  0],
       [20,  0,  0,  0, 23],
       [26,  0,  0,  0,  0]], dtype=int32)

In [153]:
for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
        if arr[row,col]>30:
            arr[row,col]=0
arr

array([[ 0, 18, 20,  0,  0],
       [13, 10,  0,  0,  0],
       [20,  0,  0,  0, 23],
       [26,  0,  0,  0,  0]], dtype=int32)

In [154]:
print(np.sum(arr))
print(arr.sum())
sum=0
for row in range(arr.shape[0]):
    for col in range(arr.shape[1]):
            sum+=arr[row,col]
print(sum)


130
130
130


In [155]:
for row in range(arr.shape[0]):
    print(arr[row].mean())

7.6
4.6
8.6
5.2


In [156]:
row_mean=np.mean(arr, axis=1)
row_mean

array([7.6, 4.6, 8.6, 5.2])

In [158]:
new_row=np.random.randint(10,61, size=(1,5))
new_row

array([[33, 43, 55, 30, 24]], dtype=int32)

In [159]:
new_arr=np.vstack((arr, new_row))
new_arr

array([[ 0, 18, 20,  0,  0],
       [13, 10,  0,  0,  0],
       [20,  0,  0,  0, 23],
       [26,  0,  0,  0,  0],
       [33, 43, 55, 30, 24]], dtype=int32)